turismo/config/routes.rb
Rails.application.routes.draw do
  resources :photos
  resources :comments
  resources :categories
  resources :sites

  devise_for :users

   root 'home#index'

  get 'index_per_price' => 'sites#index_per_price', as: :index_per_price

end

turismo/app/models/site.rb
class Site < ActiveRecord::Base
	has_many :photos
	belongs_to :category
	has_many :comments

	mount_uploader :image, AvatarUploader
	mount_uploader :image_name, AvatarUploader

end

turismo/app/controllers/sites_controller.rb
class SitesController < ApplicationController
  before_action :set_site, only: [:show, :edit, :update, :destroy]
  #before_action :authenticate_user!, only: [:create, :update, :destroy, :new]

  # GET /sites
  # GET /sites.json
  def index
    category_id =  params[:category_id]
    @sites = Site.where(category_id: category_id)
  end

  def index_per_price
    price =  params[:price]
    @sites = Site.where(" price <= ? ", price)
  end

  # GET /sites/1
  # GET /sites/1.json
  def show
  end

  # GET /sites/new
  def new
    @site = Site.new
  end

  # GET /sites/1/edit
  def edit
  end

  # POST /sites
  # POST /sites.json
  def create
    @site = Site.new(site_params)

    respond_to do |format|
      if @site.save
        format.html { redirect_to @site, notice: 'Site was successfully created.' }
        format.json { render :show, status: :created, location: @site }
      else
        format.html { render :new }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sites/1
  # PATCH/PUT /sites/1.json
  def update
    respond_to do |format|
      if @site.update(site_params)
        format.html { redirect_to @site, notice: 'Site was successfully updated.' }
        format.json { render :show, status: :ok, location: @site }
      else
        format.html { render :edit }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sites/1
  # DELETE /sites/1.json
  def destroy
    @site.destroy
    respond_to do |format|
      format.html { redirect_to sites_url, notice: 'Site was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_site
      @site = Site.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def site_params
      params.require(:site).permit(:name, :image_name, :image, :description, :location, :address, :contact, :category_id, :price)
    end
end

turismo/app/helpers/sites_helper.rb
module SitesHelper
end

turismo/app/views/sites/_form.html.erb
<%= form_for(@site) do |f| %>
  <% if @site.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@site.errors.count, "error") %> prohibited this site from being saved:</h2>

      <ul>
      <% @site.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :image_name %><br>
    <%= f.file_field :image_name %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_area :location %>
  </div>
    <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :contact %><br>
    <%= f.text_area :contact %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.number_field :category_id %>
  </div>
    <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

turismo/app/views/sites/edit.html.erb
<h1>Editing Site</h1>

<%= render 'form' %>

<%= link_to 'Show', @site %> |
<%= link_to 'Back', sites_path %>

turismo/app/views/sites/index.html.erb
<div class="bodyTwo">
	<header>
 <div class="logo">
  </div>
  
</header>
<div class="slogan">
	<p>Sitios de interés  y turísticos</p>
</div>

<div class="row imagenSitio">
    <% @sites.each do |site| %>
	 
     <div class="col-xs-6 col-md-3 col-lg-2">
	 	 <%= link_to(site) do %>	
	     	<%= image_tag site.image_name.url %>
	     <% end %>
     </div>
     <%#= link_to 'Edit', edit_site_path(site) %>
   
    <% end %>

   </div>

<%= link_to 'New Site', new_site_path %>
</div>

<footer>
  
</footer>

turismo/app/views/sites/index_per_price.html.erb
<header>
 <div class="logo">
  </div>
  
</header>

<div class="slogan">

</div>
<h1>Lugares a tu alcance</h1>

<% @sites.each do |index_per_price| %>
	<%= link_to(index_per_price) do %>	
	     	<%= index_per_price.name %></br>
	     <% end %>
<% end %>

<footer>
	
</footer>

turismo/app/views/sites/new.html.erb
<h1>New Site</h1>

<%= render 'form' %>

<%= link_to 'Back', sites_path %>

turismo/app/views/sites/show.html.erb
<div class="bodyTwo">
  <header>
 <div class="logo">
  </div>
  
</header>

<div class="slogan">
  <p><%= @site.name %></p>
</div>

<p class="image_content">
<%= image_tag @site.image.url %>
</p>

<div class="information">
<p class="description">
  <%= @site.description %>
</p>

<p>
  <strong>Ubicación: </strong><%= @site.location %>
</p>

<p>
  <strong>Dirección: </strong><%= @site.address %>
</p>

<p>
<%= @site.contact %>
</p>
</div>


<!-- <p>
  <strong>Category:</strong>
  <%= @site.category_id %>
</p> -->

</div>

<footer>
	<%= link_to 'Edit', edit_site_path(@site) %> |
	<%= link_to 'Back', categories_path %>
</footer>