turismo/config/routes.rb
Rails.application.routes.draw do
  resources :photos
  resources :comments
  resources :categories
  resources :sites

  devise_for :users

   root 'home#index'

  get 'index_per_price' => 'sites#index_per_price', as: :index_per_price

end

turismo/app/models/category.rb
class Category < ActiveRecord::Base
	has_many :sites

end

turismo/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

turismo/app/helpers/categories_helper.rb
module CategoriesHelper
end

turismo/app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

turismo/app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

turismo/app/views/categories/index.html.erb
<div class="body bodyTwo">

<header>
 <div class="logo">
	</div>

		<% if user_signed_in? %>
			<%= current_user.email %>
			<%= link_to "Logout", destroy_session_path(current_user), method: 
			:delete %><br />
		<% end %>
	
</header>
<div class="slogan">
    <p>Sitios de interés  y turísticos</p>
</div>
<div class="slider">
    <ul id="images">
    <li class="image"><%= image_tag "slider/explora_slider.jpg"%></li>
    <li class="image"><%= image_tag "slider/flores_slider.jpg"%></li>
    <li class="image"><%= image_tag "slider/jardin_slider.jpg"%></li>
    <li class="image"><%= image_tag "slider/navidad_slider.jpg"%></li>
    <li class="image"><%= image_tag "slider/plaza_slider.jpg"%></li>

        <!-- <li class="image"><img src="explora_slider.jpg"></li> 
        <li class="image"><img src="flores_slider.jpg"></li>
        <li class="image"><img src="jardin_slider.jpg"></li>
        <li class="image"><img src="navidad_slider.jpg"></li>
        <li class="image"><img src="plaza_slider.jpg"></li> -->
    </ul>
    
    <ul id="botones">
        <li>1</li>
        <li>2</li>
        <li>3</li>
        <li>4</li>
        <li>5</li>
    </ul>
    
    <a id="anterior" href"#">
    <div id="TrianguloIzquierda"></div>
    </a>
    
    <a id="siguiente" href"#">
    <div id="TrianguloDerecha"></div>
    </a>
</div>
    <nav>
      <ul>

    <% @categories.each do |category| %>

        <li><%= link_to category.name, sites_path(category_id: category.id) %></li>


    <% end %>

       </ul>
    </nav>
</div>

    <footer>
        <div class="atras"><%= link_to 'Atrás', root_path %></div>
    </footer>

turismo/app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

turismo/app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>